services:
  - type: web
    name: odoo-sms-integration
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn app:app
    plan: free
    region: virginia
    branch: main
    healthCheckPath: /
